#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
# Customize to your needs...
[[ -s "$HOME/.zshrc-local" ]] && . "$HOME/.zshrc-local"

# unalias
unalias grc

mkgo (){
		mkdir -p $1 && cd $1
}

autoload predict-on
predict-toggle() {
  ((predict_on=1-predict_on)) && predict-on || predict-off
}
  zle -N predict-toggle
  bindkey '^Z'   predict-toggle
  zstyle ':predict' toggle true
  zstyle ':predict' verbose true



 # Tool Shortcuts
 alias mci='mvn clean install'

 alias gradle='gradle --daemon'
 alias gi='gradle install --daemon'
 alias gci='gradle clean install --daemon'

# Tmux

alias ta='tmux attach || tmux new'

 # fasd shortcuts
 alias a='fasd -a'        # any
 alias s='fasd -si'       # show / search / select
 alias d='fasd -d'        # directory
 alias f='fasd -f'        # file
 alias sd='fasd -sid'     # interactive directory selection
 alias sf='fasd -sif'     # interactive file selection

alias v='f -t -e vim -b viminfo' #fasd wrapper for vi
