# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
# Customize to your needs...
[[ -s "$HOME/.zshrc-local" ]] && . "$HOME/.zshrc-local"

autoload predict-on
predict-toggle() {
  ((predict_on=1-predict_on)) && predict-on || predict-off
}
  zle -N predict-toggle
  bindkey '^Z'   predict-toggle
  zstyle ':predict' toggle true
  zstyle ':predict' verbose true

# ls replacement
 alias ls='colorls --gs --light'
 alias ll='ls -l'
 alias la='ll -A'

# Application Shortcuts
alias of="open ."


# git aliases
alias gup='git pull --rebase'
alias gfp='gp --force-with-lease'

gclb() {
  git branch -r | awk '{print $1}' | egrep -v -f /dev/fd/0 <(git branch -vv | grep origin) | awk '{print $1}' | xargs git branch -D
}

alias v='f -t -e vim -b viminfo' #fasd wrapper for vi

# tabtab source for packages
# uninstall by removing these lines
[[ -f ~/.config/tabtab/__tabtab.zsh ]] && . ~/.config/tabtab/__tabtab.zsh || true

